package com.chinaso.greendaodemo;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cool.hello.greenDB.Card;
import com.cool.hello.greenDB.Device;
import com.cool.hello.greenDB.Person;
import com.cool.hello.greenDB.Space;
import com.cool.hello.greenDB.User;

import com.chinaso.greendaodemo.CardDao;
import com.chinaso.greendaodemo.DeviceDao;
import com.chinaso.greendaodemo.PersonDao;
import com.chinaso.greendaodemo.SpaceDao;
import com.chinaso.greendaodemo.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cardDaoConfig;
    private final DaoConfig deviceDaoConfig;
    private final DaoConfig personDaoConfig;
    private final DaoConfig spaceDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CardDao cardDao;
    private final DeviceDao deviceDao;
    private final PersonDao personDao;
    private final SpaceDao spaceDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cardDaoConfig = daoConfigMap.get(CardDao.class).clone();
        cardDaoConfig.initIdentityScope(type);

        deviceDaoConfig = daoConfigMap.get(DeviceDao.class).clone();
        deviceDaoConfig.initIdentityScope(type);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        spaceDaoConfig = daoConfigMap.get(SpaceDao.class).clone();
        spaceDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        cardDao = new CardDao(cardDaoConfig, this);
        deviceDao = new DeviceDao(deviceDaoConfig, this);
        personDao = new PersonDao(personDaoConfig, this);
        spaceDao = new SpaceDao(spaceDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Card.class, cardDao);
        registerDao(Device.class, deviceDao);
        registerDao(Person.class, personDao);
        registerDao(Space.class, spaceDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        cardDaoConfig.clearIdentityScope();
        deviceDaoConfig.clearIdentityScope();
        personDaoConfig.clearIdentityScope();
        spaceDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public CardDao getCardDao() {
        return cardDao;
    }

    public DeviceDao getDeviceDao() {
        return deviceDao;
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public SpaceDao getSpaceDao() {
        return spaceDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
