package com.chinaso.greendaodemo;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.cool.hello.greenDB.Space;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SPACE".
*/
public class SpaceDao extends AbstractDao<Space, Long> {

    public static final String TABLENAME = "SPACE";

    /**
     * Properties of entity Space.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SpaceId = new Property(1, String.class, "spaceId", false, "SPACE_ID");
        public final static Property SpaceName = new Property(2, String.class, "spaceName", false, "SPACE_NAME");
    }

    private DaoSession daoSession;


    public SpaceDao(DaoConfig config) {
        super(config);
    }
    
    public SpaceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SPACE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SPACE_ID\" TEXT," + // 1: spaceId
                "\"SPACE_NAME\" TEXT);"); // 2: spaceName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SPACE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Space entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String spaceId = entity.getSpaceId();
        if (spaceId != null) {
            stmt.bindString(2, spaceId);
        }
 
        String spaceName = entity.getSpaceName();
        if (spaceName != null) {
            stmt.bindString(3, spaceName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Space entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String spaceId = entity.getSpaceId();
        if (spaceId != null) {
            stmt.bindString(2, spaceId);
        }
 
        String spaceName = entity.getSpaceName();
        if (spaceName != null) {
            stmt.bindString(3, spaceName);
        }
    }

    @Override
    protected final void attachEntity(Space entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Space readEntity(Cursor cursor, int offset) {
        Space entity = new Space( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // spaceId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // spaceName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Space entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSpaceId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSpaceName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Space entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Space entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Space entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
